import {
  BarChart2,
  Activity,
  Search,
  Eye,
  CalendarDays,
  ImageIcon,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface Service {
  id: string;
  label: string;
  icon: LucideIcon;
  href: string;
  description: string;
  milestone: 1 | 2;
  comingSoon: boolean;
  legacy?: boolean;
}

export const SERVICES_REGISTRY: Service[] = [
  {
    id: 'gallery',
    label: 'Gallery',
    icon: ImageIcon,
    href: '/services/gallery',
    description:
      'Centralized gallery to upload, manage, and analyze raw media assets.',
    milestone: 1,
    comingSoon: false,
  },
  {
    id: 'object-count',
    label: 'Object Count',
    icon: BarChart2,
    href: '/services/object-counting',
    description:
      'Count and track unique items across 80 COCO classes, with customizable vehicle and gender classification.',
    milestone: 1,
    comingSoon: false,
    legacy: true,
  },
  {
    id: 'activity-detection',
    label: 'Activity Detection',
    icon: Activity,
    href: '/services/activity-detection',
    description:
      'Flag suspicious events with timestamps, screenshots, and video clips.',
    milestone: 1,
    comingSoon: false,
    legacy: true,
  },
  {
    id: 'person-search',
    label: 'Person Search',
    icon: Search,
    href: '/services/person-search',
    description:
      'Find anyone across hours of footage using visual similarity matching.',
    milestone: 1,
    comingSoon: false,
    legacy: false,
  },
  {
    id: 'people-analytics',
    label: 'People Analytics',
    icon: Eye,
    href: '/services/people-analytics',
    description:
      'CCTV video counting, interactive entry/exit crossing gate, and occupancy analytics.',
    milestone: 1,
    comingSoon: false,
    legacy: true,
  },
  {
    id: 'attendance',
    label: 'Attendance',
    icon: CalendarDays,
    href: '/services/attendance',
    description:
      'Manage employee registry, upload photos or videos, and track attendance logs.',
    milestone: 1,
    comingSoon: false,
    legacy: false,
  },
];

export const COCO_CLASSES = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
];
